### ISSUE TITLE
locating Ansys path

### ISSUE THREAD

**Issue by mmohamadsalehi** [pyansys/DPF-Post#20]
When I want to load solution using the following code, I get this error message:
"ValueError: Unable to automatically locate the Ansys path.  Manually enter one when starting the server or set it as the environment variable "ANSYS_PATH" ''
Here, is my code:
from ansys.dpf import post
solution = post.load_solution('/home/user/file.rst')

**Comment by cbellot000** [comment]
Thanks for writing this issue,
The python client is looking for an install of ansys 2021R1, is it installed on your machine? If yes can you the environment variable ANSYS_PATH to your folder .../AnsysInc/v211?

**Comment by yeguang-xue** [comment]
Probably should be discussed on repo DPF-Core. But when I look at the code of "DPF-Core/ansys/dpf/core/server.py" Line 197 to Line 205:

```
if os.name == 'posix':
    if 'ubuntu' in platform.platform().lower():
        raise OSError('DPF does not support Ubuntu')
    raise NotImplementedError()
    # self._process = launch_linux_local()
elif os.name == 'nt':
    self._process = launch_dpf_windows(ansys_path, ip, port)
else:
    NotImplementedError('OS {os.name} not supported')
```

The dpf server is not implemented for Linux yet?

**Comment by cbellot000** [comment]
Sorry I didn't get that you were working on linux, if that's the case, you need to start the server yourself on linux in 2021R1, by launching the executable (Ans.Dpf.Grpc.exe in v211/aisol/bin/linx64) and then use the connect_to_server method instead of start_local_server.
Although, you should set the paths so that the exe can find its runtime dependencies with a shell script like that:
[Ans.Dpf.Grpc211.txt](https://github.com/pyansys/DPF-Post/files/6691875/Ans.Dpf.Grpc211.txt)

Sorry for the inconvenience, the start_local_server has been implemented for linux for the 2021R2 version.

**Comment by yeguang-xue** [comment]
Great! Thanks for providing the workaround and looking to the new version!

**Comment by akaszynski** [comment]
Closing as this has been solved.
